name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: 6.0.403
  ACRNAME: handsonakspipeline

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "appId": "${{ secrets.APP_ID }}",
              "password": "${{ secrets.APP_PASSWORD }}",
              "tenant": "${{ secrets.TENANT_ID }}"
            }

      - name: ACR Login
        run: az acr login -n ${{ env.ACRNAME }}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: ./Chapter15
          push: true
          tags: ${{ env.ACRNAME }}.azurecr.io/website/website:${{ github.run_number }}
